### ISSUE TITLE
Update not work on synology NAS.

### ISSUE THREAD

**Issue by aston314** [MrKsey/torrserver#1]
today at 11:00:12 PM Tue Oct 19 23:00:12 CST 2021: Start checking for TorrServer updates ...
today at 11:00:13 PM wget: missing URL
today at 11:00:13 PM Usage: wget [OPTION]... [URL]...
today at 11:00:13 PM
today at 11:00:13 PM Try `wget --help' for more options.
today at 11:00:13 PM chmod: cannot access '/TS/updates/TorrServer': No such file or directory
today at 11:00:13 PM /start_TS.sh: 35: /update_TS.sh: /TS/updates/TorrServer: not found
today at 11:00:13 PM Error during the update process: no internet access or the downloaded file is corrupted.
today at 11:00:13 PM Finished checking for updates.
today at 11:00:13 PM

**Comment by MrKsey** [comment]
> today at 11:00:12 PM Tue Oct 19 23:00:12 CST 2021: Start checking for TorrServer updates ... today at 11:00:13 PM wget: missing URL today at 11:00:13 PM Usage: wget [OPTION]... [URL]... today at 11:00:13 PM today at 11:00:13 PM Try `wget --help' for more options. today at 11:00:13 PM chmod: cannot access '/TS/updates/TorrServer': No such file or directory today at 11:00:13 PM /start_TS.sh: 35: /update_TS.sh: /TS/updates/TorrServer: not found today at 11:00:13 PM Error during the update process: no internet access or the downloaded file is corrupted. today at 11:00:13 PM Finished checking for updates. today at 11:00:13 PM

Fixed. Please reinstall container (stop->delete->create and run)
