### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by Anzic23** [MrKsey/torrserver#2]
А как обновиться на крайнюю 111 версию сервера? контейнер запустил, но не нашел опции обновления

**Comment by Anzic23** [comment]
Получилось обновить раскоментировав следующие строки в ts.ini
TS_UPDATE="true"
cron_task="32 20 * * *"

**Comment by MrKsey** [comment]
По-умолчанию, контейнер обновляется только при перезагрузке.
Если раскомментировали cron, то будет обновляться и при перезагрузке и по расписанию.
