### ISSUE TITLE
Something about download data after docker reboot

### ISSUE THREAD

**Issue by aston314** [MrKsey/torrserver#4]
stdout: 0 upgraded, 169 newly installed, 0 to remove and 0 not upgraded.
stdout: Need to get 82.6 MB of archives.
stdout: After this operation, 1174 MB of additional disk space will be used

Why do I must download so big data every time I reboot the docker?

**Comment by MrKsey** [comment]
> stdout: 0 upgraded, 169 newly installed, 0 to remove and 0 not upgraded. stdout: Need to get 82.6 MB of archives. stdout: After this operation, 1174 MB of additional disk space will be used
> 
> Why do I must download so big data every time I reboot the docker?

Sorry. Fixed.
Please remove the old container/image, install the new from hub.docker.com

**Comment by aston314** [comment]
Good
